### ISSUE TITLE
Can we use it for multiple accounts?

### ISSUE THREAD

**Issue by saifabbasi** [atymic/twitter#100]
Currently due to hard coded values in env, it can be used for one account, is there a way to use it with dynamic access tokens? or do we need to overwrite the class and make it according to this need?

**Comment by dmyers** [comment]
The config options are for an application. You ask users (accounts) to authorize your application access to their data. So it works with multiple user accounts, or do you mean multiple applications?

**Comment by LunarDevelopment** [comment]
I have pretty much the same question as @saifabbasi so maybe we're both missing something. 

I'm using Satellizer for AngularJS and Laravel, the only twitter variables that I've had to hard code for my app to allow per-users to log into their twitter via my app are : 

'twitter_key' => 'xxxxxxxxxxxxxxxxxxxxxx',
'twitter_secret' => 'xxxxxxxxxxxxxxxxxxxxxx',
'twitter_callback' => 'http://127.0.0.1:8000/auth/twitter',

So the other variables we're told in the readme to set as static in the .env file appear to me to be user specific variables ? Meaning you'd have to hard code which twitter user your entire laravel app is for? 

I hope this makes sense.

**Comment by LunarDevelopment** [comment]
Never mind, found the answer, 

in the apps.twitter portal there is 2 sections under "Keys and Access Tokens" and your access tokens are there, see this question and following page for more details: 
https://twittercommunity.com/t/access-token-secret/525
https://dev.twitter.com/oauth/overview/application-owner-access-tokens

**Comment by YOzaz** [comment]
I'm using this package for multiple accounts, through the same app. There's a method `reconfigure` for this purpose, where you can pass new `token` and `secret` values. The only caveat - you need to keep whole local config in your class to maintain key and secret values.
I've made a wrapper class for it, pasting it here - maybe you'll find it useful.
```php
class TwitterWrapper
{
   protected $config = [];

   public function __construct()
   {
      $this->setConfig([
         'consumer_key' => env('YOUR_KEY_VALUE'),
         'consumer_secret' => env('YOUR_SECRET_VALUE'),
      ]);
   }

   protected function setConfig( $config = [] )
   {
      $this->config = array_replace_recursive( $this->config, $config );
      Twitter::reconfig( $this->config );
   }

   public function setToken( $token, $secret )
   {
      $this->setConfig([
         'token'     => $token,
         'secret'     => $secret,
      ]);
   }
}

// Usage example
$twitter = new TwitterWrapper();
// Set dynamic token
$twitter->setToken( $dynamic_token, $dynamic_secret );
// ... make your calls
Twitter::post(...);
```
As `Twitter` class is static / singleton, you should be able to make calls safely after wrapper config.
Alternatively, you can make wrapper methods to call similar `Twitter` methods as well - it may even be useful, to parse additional data, etc.

**Comment by AmrMekkawy** [comment]
I have faced the same problem of publishing on multiple twitter accounts and I've solved it like this:
```
// set data of the twitter account you are going to publish to..
if (some_condition) {
    $consumer_key =  "account_consumer_key";
    $consumer_secret =  "account_consumer_secret";
    $access_token = "account_access_token";
    $access_token_secret = "account_access_token_secret";
} else if (some_condition) {
    $consumer_key =  "account_consumer_key";
    $consumer_secret =  "account_consumer_secret";
    $access_token = "account_access_token";
    $access_token_secret = "account_access_token_secret";
}

Twitter::reconfig([
	"consumer_key" => $consumer_key,
	"consumer_secret"  => $consumer_secret,
	"token" => $access_token,
	"secret" => $access_token_secret,
]);

$tweet = [
	'status' => "Put the 140 characters that you are going to publish to twitter here",
];

$tweet_result = Twitter::postTweet($tweet);
```

Credits goes to: https://goo.gl/QugXXC

**Comment by sadafrasheed** [comment]
> I'm using this package for multiple accounts, through the same app. There's a method `reconfigure` for this purpose, where you can pass new `token` and `secret` values. The only caveat - you need to keep whole local config in your class to maintain key and secret values.
> I've made a wrapper class for it, pasting it here - maybe you'll find it useful.
> 
> ```
> class TwitterWrapper
> {
>    protected $config = [];
> 
>    public function __construct()
>    {
>       $this->setConfig([
>          'consumer_key' => env('YOUR_KEY_VALUE'),
>          'consumer_secret' => env('YOUR_SECRET_VALUE'),
>       ]);
>    }
> 
>    protected function setConfig( $config = [] )
>    {
>       $this->config = array_replace_recursive( $this->config, $config );
>       Twitter::reconfig( $this->config );
>    }
> 
>    public function setToken( $token, $secret )
>    {
>       $this->setConfig([
>          'token'     => $token,
>          'secret'     => $secret,
>       ]);
>    }
> }
> 
> // Usage example
> $twitter = new TwitterWrapper();
> // Set dynamic token
> $twitter->setToken( $dynamic_token, $dynamic_secret );
> // ... make your calls
> Twitter::post(...);
> ```
> 
> As `Twitter` class is static / singleton, you should be able to make calls safely after wrapper config.
> Alternatively, you can make wrapper methods to call similar `Twitter` methods as well - it may even be useful, to parse additional data, etc.

This should be added to ReadMe or a Wiki for this package.
Thanks a lot man

**Comment by ivanraybuglosa** [comment]
> I have faced the same problem of publishing on multiple twitter accounts and I've solved it like this:
> 
> ```
> // set data of the twitter account you are going to publish to..
> if (some_condition) {
>     $consumer_key =  "account_consumer_key";
>     $consumer_secret =  "account_consumer_secret";
>     $access_token = "account_access_token";
>     $access_token_secret = "account_access_token_secret";
> } else if (some_condition) {
>     $consumer_key =  "account_consumer_key";
>     $consumer_secret =  "account_consumer_secret";
>     $access_token = "account_access_token";
>     $access_token_secret = "account_access_token_secret";
> }
> 
> Twitter::reconfig([
>     "consumer_key" => $consumer_key,
>     "consumer_secret"  => $consumer_secret,
>     "token" => $access_token,
>     "secret" => $access_token_secret,
> ]);
> 
> $tweet = [
>     'status' => "Put the 140 characters that you are going to publish to twitter here",
> ];
> 
> $tweet_result = Twitter::postTweet($tweet);
> ```
> 
> Credits goes to: https://goo.gl/QugXXC

I saw and understand this tutorial. But how do we let users post tweets that are not in our company? And doesn't have twitter API credentials?

**Comment by vishalinfyom** [comment]
Can i get events when some other user follow someone ?

**Comment by atymic** [comment]
Update to v3, it's much easier now.
```
$twitterForSpecificUser = Twitter::withOauthCredentials($accessToken, $accessTokenSecret);
```

**Comment by robjbrain** [comment]
Just a note to anyone else stumbling on this the example by atymic above is wrong. It should be:

```php
$twitterForSpecificUser = Twitter::usingCredentials($accessToken, $accessTokenSecret);
```

This is in the docs already, it's only the example posted in this issue which is wrong and I just wanted to avoid anyone else being confused as I was briefly :)
