### ISSUE TITLE
Please add this new function

### ISSUE THREAD

**Issue by abhisheksrivastav** [atymic/twitter#152]
Hi Thujon,

Thank you for providing such a nice library for twitter.

Could you please add a new method in Status trait.
thujohn/twitter/src/Thujohn/Twitter/Traits/StatusTrait.php
for 

```
<?php namespace Thujohn\Twitter\Traits;

   //method for undo retweet option
   public function undoRt($id, $parameters = [])
    {
        return $this->post('statuses/unretweet/'.$id, $parameters);
    }
```

it would be very helpful.

Thanks,
Abhishek

**Comment by atymic** [comment]
Is this still missing?
