### ISSUE TITLE
Status with new line

### ISSUE THREAD

**Issue by rikkeisoft-dn** [atymic/twitter#194]
I want to post a twitter with new line.
How can I do it?

**Comment by pajoda** [comment]
https://twittercommunity.com/t/is-it-possible-to-add-a-line-feed-to-a-status-update/7628

But I'm not sure about Twitter actually displaying the line break. See another post about it in another language, but that's not the point of the comment: http://stackoverflow.com/questions/15122284/post-tweet-with-new-line-inside-it

**Comment by phongnd1609** [comment]
@pajoda 
Thanks for your answer.
I have tried above link, but twitter can not display the line break.
Twitter::postTweet(array('This is first sentence'.'%0D%0A'.'This is second sentence', 'format' => 'json'));

**Comment by kiksy** [comment]
I think the issue is in Twitter.php
line 244:

`$this->log('PARAMETERS : '.http_build_query($parameters));`

`http_build_query()`

will return the url encoded:

> This+is+first+sentence+%250D%250A+This+is+second+sentence

Which when tweeted looks like:

> This is first sentence %0D%0A This is second sentence

However, we want to pass to Twitter:

> This+is+first+sentence+%0A+This+is+second+sentence

For proof of a solution you can edit the $parameters variable in the query method within Twitter.php to

```
        if($name !== "media/upload")
        {
            $parametersEncoded = http_build_query($parameters);
            $parametersEncoded = str_replace("%250A", "%0A", $parametersEncoded);
        }
        else
        {
            $parametersEncoded = http_build_query($parameters);
        }


	$this->log('METHOD : '.$requestMethod);
	$this->log('QUERY : '.$name);
	$this->log('URL : '.$url);
	$this->log('PARAMETERS : '.$parametersEncoded);
	$this->log('MULTIPART : '.($multipart ? 'true' : 'false'));
```

**Comment by dawidmierzwa95** [comment]
Try this:
`       $string = 'Next 24h events: ';
       $newLine = '
            ';
        $newLine = str_replace(' ', '', $newLine);
        $string = $string.$newLine;
`
its work for me ($newLive has to broken )

**Comment by safakz** [comment]
I ended up adding urldecoded newline char
`$status = 'First line'. urldecode('%0a').'Second line'.urldecode('%0a').'Third line';`
I hope it will help others...

**Comment by milanchheda** [comment]
You can use "\n" for newline.

Example:
`$status = "First line. \nSecond line. \nThird line";`
