### ISSUE TITLE
extend mode for twitts

### ISSUE THREAD

**Issue by shahin-developer** [atymic/twitter#195]
hi :)
i want to get complete  twits but i lost some chars of twits,please help me to catch complete and full text of user's twits
tnx :)

**Comment by pajoda** [comment]
Hey there,

take a look into my pull request: https://github.com/thujohn/twitter/pull/193
Twitter changed the API some time ago, you need to pass a new parameter in order to get the full text instead of a text, which is truncated.

Best regards

**Comment by shahin-developer** [comment]
can you please tell me how can use it ?
$twit =  Twitter::getUserTimeline(['screen_name' => $user, 'count' => 1, 'format' => 'object']);
i use that method , should I send extra param ??

**Comment by pajoda** [comment]
I documented it here: https://github.com/thujohn/twitter/pull/193/commits/231155a0356eb38cb700def3a5245303e015a5a9#diff-53c61661742fb9396e8c49d50e14818cR57

You need to pass the parameter tweet_mode with a value of 'extended'.
Important: The response of the API will return the text of the Tweet in another key than the truncated text.

**Comment by interludic** [comment]
seems like still an issue

**Comment by dmsherazi** [comment]
Twitter::getUserTimeline(['screen_name' => 'dmsherazi', 'count' => 10, 'format' => 'json' , 'tweet_mode'=>'extended']);

will give you a **full_text** element instead of **text** and truncated field  will be false
