### ISSUE TITLE
tmhOAuth not found

### ISSUE THREAD

**Issue by mjanssen** [atymic/twitter#20]
Hey there,

Since the newest composer update, the class gives me errors. Any idea how to fix this?
`Class 'Thujohn\Twitter\tmhOAuth' not found`
*\* I'm still on Laravel 4.0.*

**Comment by xparthx** [comment]
I'm getting the same error on Laravel Framework version 4.2.22
I have changed "use tmhOAuth;" by "use \tmhOAuth;" in Thujohn\Twitter\Twitter.php but it still not working.

Any idea how to fix this?

**Comment by smnjuguna** [comment]
I changed from use tmhOAuth; to use Thujohn\Twitter\tmhOAuth;
It works perfectly.
