### ISSUE TITLE
Allow uploading videos

### ISSUE THREAD

**Issue by adnanmokhtar** [atymic/twitter#207]
i have 400 error when attempting to upload video but work with image.
here the error:

(1/1) RuntimeException[400]
--
in Twitter.php (line 304)

![screenshot-platform n-stream tv-2017-07-17-21-25-23](https://user-images.githubusercontent.com/21971198/28285895-a125bf76-6b36-11e7-87bc-6606971f12bc.png)

**Comment by KyleMassacre** [comment]
I am also getting this error when trying to use an image from Giphy

**Comment by GregKeaney** [comment]
I am getting the same error.  Any solution?

**Comment by KyleMassacre** [comment]
Well here is what I did and maybe it will work for anyone else.
```php
$giphy = new Client();
$res = $giphy->get('https://api.giphy.com/v1/gifs/randomapi_key=xxxxxxxx&tag=xxxxxxxxx&rating=PG-13')->getBody();
$data = json_decode($res);
$image = (! str_contains('https', $data->data->fixed_width_downsampled_url) ? $data->data->fixed_width_downsampled_url : str_replace('http', 'https', $data->data->fixed_width_downsampled_url));
$file = file_get_contents($image);
$tweetedImage = Twitter::uploadMedia([
    'media' => $file,
]);
$postTweet = Twitter::postTweet([
    'status'    => $tweet,
    'media_ids' => $tweetedImage->media_id_string,
});
```

**Comment by GregKeaney** [comment]
Thanks for the reply Kyle.  I also finally got it to work.  Pretty lacking API docs on Twitters part - IMO.

**Comment by scottybo** [comment]
Just in case someone else finds this thread, I've forked this package and added video support (docs for video near the bottom of the readme): https://github.com/scottybo/twitter

**Comment by atymic** [comment]
Can we do this in 3.x @reliq?

**Comment by atymic** [comment]
Sorry, closing in favour of #62
