### ISSUE TITLE
Class 'Twitter' not found

### ISSUE THREAD

**Issue by vijaymgr** [atymic/twitter#223]
Hello, while implementing this plugin, I am getting an error as: 

Class 'Twitter' not found

What I have done: 

update composer.json

"thujohn/twitter": "~2.0"
Run composer update

In config/app.php and added the service provider

'providers' => [
	Thujohn\Twitter\TwitterServiceProvider::class,
]

added aliases:

'aliases' => [
	'Twitter' => Thujohn\Twitter\Facades\Twitter::class,
]

In top of my controller, I import the twitter as  
use Twitter;

but still getting the error 

Class 'Twitter' not found

Please help

**Comment by hsntngr55** [comment]
Same here (Laravel 5.6) Packeage not publish as well, there is no config file in config folder

**Comment by hsntngr55** [comment]
I found it bro, check your package files they shoud have enough permission. Or you can easly use `sudo` command like below.
```
sudo php artisan vendor:publish --provider="Thujohn\Twitter\TwitterServiceProvider"
```

**Comment by vijayrana-me** [comment]
thanks for the info but I am using windows so, its a bit different in my case

**Comment by hsntngr55** [comment]
what's matter ? you have a linux os in your virtual box right ?

**Comment by mohitpawar10** [comment]
Run **composer dumpautoload**. It will dump all previous classes and generate the new class map.

**Comment by Naveedali1234** [comment]
i have the same issue. class 'Twitter' not found, while i configured everything as required, but no luck. Please help us out on this issue.

**Comment by hsntngr55** [comment]
@Naveedali1234  Did you published as well ? Are you sure about that ? Because at the first, I published and there was no error abut that and I realized, package didin't published correctly, even twitter.app not in config file. So give 777 permission to twitter file (in vendor) than I published again. That solution was worked for me

**Comment by Naveedali1234** [comment]
I added this in my config/app.php file
`'providers' => [
	Thujohn\Twitter\TwitterServiceProvider::class,
]`
and in aliases array
`'aliases' => [
	'Twitter' => Thujohn\Twitter\Facades\Twitter::class,
]`
i run this command to publish the config/ttwitter.php file
`php artisan vendor:publish --provider="Thujohn\Twitter\TwitterServiceProvider"`
and i got response on cmd "publishing complete"

But there is no ttwitter.php file in config folder. 
in my controller i used `use Twitter` for namespace
But still i am getting an exception of "class 'Twitter' not found "

**Comment by Naveedali1234** [comment]
where should i give the 777 permission for Twitter file. Please guide me on it. I don't have much knowledge about file permissions. Your Help would be appreciated, for me and also for others who have the same issue.

**Comment by hsntngr55** [comment]
Can you try just like that;
sudo php artisan vendor:publish --provider="Thujohn\Twitter\TwitterServiceProvider"

@Naveedali1234

**Comment by Naveedali1234** [comment]
i am using windows and this command doesn't work on CLI.

**Comment by hsntngr55** [comment]
@Naveedali1234  but you have linux os in your virtualbox right ?

**Comment by Naveedali1234** [comment]
i am using windows and i am running the project on my local server and i am using xampp for now. I don't have much knowledge about Laravel. Your guidance would be much appreciated.

**Comment by hsntngr55** [comment]
Sorry, I thought your workspace in virtualbox

**Comment by Naveedali1234** [comment]
so what would be the solution now? do you have any idea?

**Comment by hsntngr55** [comment]
@Naveedali1234 Can you try this in below way
```
use Thujohn\Twitter\Twitter; (or)
use Thujohn\Twitter\Facede\Twitter;
```

**Comment by Naveedali1234** [comment]
That doesn't work and gives me an error exception " Non-static method Thujohn\Twitter\Twitter::postTweet() should not be called statically".

**Comment by mohitpawar10** [comment]
in the header.
**use Twitter;**

In the code 
**Twitter::postTweet()**

Facade allows you to access non-static method statically. You will also need to add Alias in app.php in the config folder. If you are still getting the error, then try **composer dumpautoload**. Many times laravel does not recognize newly added classes, If you are still getting the same error then try **php artisan config:clear**. It will clear config cache.

**Comment by Naveedali1234** [comment]
i used `use Twitter` in the header. and in the code i used `Twitter::postTweet()` and also added an alias in app.php. but still i am getting this error of **Class Twitter not found** .

**Comment by mohitpawar10** [comment]
Did you try "composer dump-autoload"?

**Comment by Naveedali1234** [comment]
yes i have tried that so many times but no luck.

**Comment by mohitpawar10** [comment]
try following.
use Thujohn\Twitter\Facades\Twitter as Twitter.

**Comment by nordicmediagroup** [comment]
Using Larave 5.6 don't forget to run php artisan config:cache to reload the .env file

**Comment by gavinj1999** [comment]
Using Larave 5.6 don't forget to run php artisan config:cache to reload the .env file

**Comment by Majidkadi** [comment]
If you are still looking for the solution you have to add this :
      "thujohn/twitter": "~2.0"
at the end of "composer.json" file (before the la last closing bracket "}" and do not us comma "," at the end of the line)
Then run "composer update" see this link : 
https://github.com/thujohn/twitter

**Comment by Dilpenny** [comment]
For laravel users Clear cache and publish again

**Comment by atymic** [comment]
Going to close this due to inactivity. Please open a new issue if you are still having problems.

**Comment by nelsoniseru** [comment]
am using Atymic\Twitter for laravel 8 and i get this Atymic\Twitter\Laravel\ServiceProvider not found
