### ISSUE TITLE
Twitter is truncating 'text'

### ISSUE THREAD

**Issue by cloudbluedigital** [atymic/twitter#224]
So when I use
```
return Twitter::getUserTimeline(['screen_name' => 'ChadWeather', 'count' => 20, 'format' => 'array']);
```

I do get the response however the text key where the description is, is truncated and therefore I can't see a full post. Is there a way to avoid that?

**Comment by pajoda** [comment]
Hey cloudbluedigital,

you can take a look at my pull request: https://github.com/thujohn/twitter/pull/193/files#diff-53c61661742fb9396e8c49d50e14818cR39

Tweets are truncated by default for some time now. Use parameter 'tweet_mode' with value 'extended'.

**Comment by omikabira** [comment]
use 'tweet_mode'=>'extended' and it will return full tweet by replacing text to full_text

**Comment by interludic** [comment]
'tweet_mode'=>'extended' not working

**Comment by lucasctd** [comment]
It's not working... I amstill getting truncated tweet.

**Comment by dmsherazi** [comment]
` Twitter::getUserTimeline(['screen_name' => 'dmsherazi', 'count' => 10, 'format' => 'json' , 'tweet_mode'=>'extended']);`

Note` 'tweet_mode'=>'extended'`

will give you a **full_text** element instead of **text** and truncated field  will be false
