### ISSUE TITLE
If user's account doesn't exist uncatchable error 401 thrown

### ISSUE THREAD

**Issue by sdiama** [atymic/twitter#230]
When using getUserTimeline() for a user's account that doesn't exist, is deleted or is suspended, a RuntimeException in Twitter.php line 304: [401] returned.
The exception cannot be caught in a catch (Exception $e)

**Comment by rbrisita** [comment]
Have you tried catching the base class of 'Exception'?

**Comment by atymic** [comment]
All exceptions can be caught, so closing this.
