### ISSUE TITLE
Twitter Direct Message API changes

### ISSUE THREAD

**Issue by ajaykrishnalla** [atymic/twitter#243]
twitter direct message is not working , Twitter changed the direct message endpoint

**Comment by daitranthanhhoa** [comment]
change `direct_messages/new `to `direct_messages/events/new`

**Comment by ajaykrishnalla** [comment]
yes, i changed the endpoints though post parameters also changed

**Comment by atymic** [comment]
PR open here: https://github.com/atymic/twitter/pull/274
