### ISSUE TITLE
Symbol 'DB' is declared but not used.intelephense (10010)

### ISSUE THREAD

**Issue by MohamedAbd0** [atymic/twitter#253]
I want to change the read data from .env file  to read from database .

- in config.php :-

- 	'CONSUMER_KEY'        => function_exists('env') ? env('TWITTER_CONSUMER_KEY', '') : '',

- 	'CONSUMER_SECRET'     => function_exists('env') ? env('TWITTER_CONSUMER_SECRET', '') : '',

- 	'ACCESS_TOKEN'        => function_exists('env') ? env('TWITTER_ACCESS_TOKEN', '') : '',

- 	'ACCESS_TOKEN_SECRET' => function_exists('env') ? env('TWITTER_ACCESS_TOKEN_SECRET', '') : '',

**Comment by atymic** [comment]
Just configure them with default, and then you can grab an instance from the service provider and reconfigure it:

```php
$client = app(Twitter::class);
$client->reconfig([
	'access_token' => 'etc',
])
```
