### ISSUE TITLE
Getting a "ErrorException (E_NOTICE) Undefined index: text" using the Linkify function 

### ISSUE THREAD

**Issue by RezaODB** [atymic/twitter#254]
Hello,
I guess I'm doing something wrong, but I can't see what...

    function index() {
        $tweets = Twitter::getUserTimeline(['screen_name' => 'XXXXX', 'tweet_mode' => 'extended', 'count' => 3]);
        $tweets = Twitter::linkify($tweets);
        return view('welcome', compact('tweets'));
    }

Thanks for your help!

**Comment by atymic** [comment]
`Twitter::linkify` takes a single tweet, so you'll need to loop over them.

**Comment by RezaODB** [comment]
Great, thanks for taking the time to answer!

**Comment by atymic** [comment]
No worries, sorry for the delay :P
