### ISSUE TITLE
I get an error while sending message 

### ISSUE THREAD

**Issue by a-j-n** [atymic/twitter#255]
that is the error 
```
2019-06-23 16:30:02] local.INFO: RuntimeException: [34] Sorry, that page does not exist. in /var/www/html/twitter/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php:304
Stack trace:
#0 /var/www/html/twitter/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php(328): Thujohn\Twitter\Twitter->query('direct_messages...', 'POST', Array, false)
#1 /var/www/html/twitter/vendor/thujohn/twitter/src/Thujohn/Twitter/Traits/DirectMessageTrait.php(85): Thujohn\Twitter\Twitter->post('direct_messages...', Array)
#2 /var/www/html/twitter/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Thujohn\Twitter\Twitter->postDm(Array)
#3 /var/www/html/twitter/app/Console/Commands/SendMessages.php(38): Illuminate\Support\Facades\Facade::__callStatic('postDm', Array)
#4 [internal function]: App\Console\Commands\SendMessages->handle()
#5 /var/www/html/twitter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /var/www/html/twitter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www/html/twitter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
```
i think the end point for sending message is not right

**Comment by WillBallard** [comment]
Hi @a-j-n I also experienced the same issue, if you're still struggling, take a look at the API reference here: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events

It requires a different slug which is hard coded into the traits in vendor\thujohn\twitter\src\Thujohn\Twitter\Twitter.php

Please see (taken from the API reference):
POST direct_messages/events/new (message_create)
GET direct_messages/events/show
GET direct_messages/events/list
DELETE direct_messages/events/destroy

so you need to change postDm() in your case.

``
return $this->post('direct_messages/new', $parameters);
``
Now becomes:
``
return $this->post('direct_messages/events/new', $parameters);
``

**Comment by atymic** [comment]
PR open here:
https://github.com/atymic/twitter/pull/274
