### ISSUE TITLE
[0] Unknown error In Twitter.php line 304

### ISSUE THREAD

**Issue by DebasisBehera123** [atymic/twitter#257]
It was working fine a few hours before now it is showing this type of error
after I did dd(Twitter::logs());

it shows below array
array:16 [
  0 => "METHOD : GET"
  1 => "QUERY : statuses/user_timeline"
  2 => "URL : https://api.twitter.com/1.1/statuses/user_timeline.json"
  3 => "PARAMETERS : screen_name=CSMTechnologies&tweet_mode=extended&exclude_replies=false&count=200&format=array"
  4 => "MULTIPART : false"
  5 => "FORMAT : array"
  6 => "METHOD : GET"
  7 => "QUERY : statuses/user_timeline"
  8 => "URL : https://api.twitter.com/1.1/statuses/user_timeline.json"
  9 => "PARAMETERS : screen_name=CSMTechnologies&tweet_mode=extended&exclude_replies=false&count=200&max_id=1088431945753579520&format=array"
  10 => "MULTIPART : false"
  11 => "FORMAT : array"
  12 => "ERROR_CODE : 28"
  13 => "ERROR_MSG : Operation timed out after 0 milliseconds with 0 out of 0 bytes received"
  14 => "ERROR_CODE : 0"
  15 => "ERROR_MSG : Unknown error"
]

**Comment by atymic** [comment]
> Operation timed out after 0 milliseconds with 0 out of 0 bytes received

This is a network issue on your end.
