### ISSUE TITLE
how can assign multiple place to the array in getTrendsPlace ()

### ISSUE THREAD

**Issue by badrshs** [atymic/twitter#258]
as i can see `getTrendsPlace` take array parameter which should have id of the place . 

and if its an array that mean i can add multi place to the array 

how to request multiple value at the same time ? 

`	$collection =  TTwitter::getTrendsPlace(["id"=>'1937801']);`

why i'm asking because i noticed that the response even is an array of trends 

![image](https://user-images.githubusercontent.com/26596347/63287429-f9afc200-c2c2-11e9-9184-0702b99d4956.png)

any idea please ?

**Comment by atymic** [comment]
Looking at the underlying docs, there's not support for passing multiple IDs:
https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place

If you have any more questions, feel free to create them on our fork here:
https://github.com/atymic/laravel-twitter
