### ISSUE TITLE
Updating the package to work with Laravel 6

### ISSUE THREAD

**Issue by nuhu-ibrahim** [atymic/twitter#259]
Good day guys, am trying to use the Twitter package on Laravel 6 but have not been able to instal it because it only supports version 4/5. Kindly update for version 6. Thank you

**Comment by markdwhite** [comment]
There appear to be a large number of forks of this, with a number of them providing L6 support. Given the recent activity on this repo, it may well be abandoned which is a shame considering the 850k installs through Packagist. To save anyone else doing this, potential candidates for L6 support include:

**6 only**
reliqarts/thujohn-twitter
scottybo/twitter

**4, 5 & 6**
sursolar/twitter
trideout/twitter
user00265/twitter
killgt/twitter-1
FN365/twitter
diegoalvarezb/laravel-twitter
chrismou/twitter

Some of these have only updated composer.json so using that repo at the current commit should allow you to upgrade your projects to 6.0. Some repos also have work in progress to provide other functionality and I've not dug deep into those changes.

**Comment by atymic** [comment]
Hey all.

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects (needed laravel 6 support, mainly.

https://github.com/atymic/laravel-twitter

I plan to start going through the bugs/feature requests and adding support them to my fork. I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
Support for Laravel 6 has been added and will be tagged shortly 😄
