### ISSUE TITLE
Not longer supported?

### ISSUE THREAD

**Issue by jozeflambrecht** [atymic/twitter#261]
Seems like the last commit was 2 years ago.. Is this package dead? @thujohn Do you need help to maintain?

**Comment by markdwhite** [comment]
On #259 I've just added a list of forked packages that offer L6 support as this is probably the key thing we need from this package right now. It's also possible that one of the forkers (forkees?) might be up for becoming the maintainer of a replacement for this package as it does appear to be abandoned.

So I've added an issue to the following to see what the response is:

scottybo/twitter

None of the other potential repos have issues enabled. Some have emails in the profile so the owners of these repos have been contacted:

reliqarts/thujohn-twitter
chrismou/twitter
user00265/twitter

And I'm not sure how to contact the remainders. Any ideas?

sursolar/twitter
trideout/twitter
killgt/twitter-1
FN365/twitter
diegoalvarezb/laravel-twitter

**Comment by reliq** [comment]
Hey @markdwhite. I intend to maintain the fork at https://github.com/reliqarts/thujohn-twitter going forward.

**Comment by scottybo** [comment]
@markdwhite  yes I'd be happy to become the new 'official' maintainer of this package - we use this package for www.chooseholly.com and will need it updated for many years to come

**Comment by scottybo** [comment]
Just to add, happy to maintain this in conjunction with other people such as @reliq

**Comment by markdwhite** [comment]
@scottybo  @reliq 

Thanks for the positive responses :-) 

I'm not sure if this is the right way to approach a takeover of an abandoned repo, so I have no idea of what happens now. It does make sense to have more than one maintainer given what happened with this package having a sole maintainer, so do you two just agree which of your repos becomes the official one or is something more required?

I also notice that some packages on Packagist are noted as 'abandoned - use xxx/yyy'. Ideally this is something that should be done with thujohn/twitter if it's agreed that makes sense. 

Is there anything else that needs to be considered?

**Comment by scottybo** [comment]
Ideally we need to get @thujohn involved in this conversation

**Comment by markdwhite** [comment]
@scottybo 

I've sent a contact on his web form
Skype address is no longer valid
Twitter is dormant since 2015 but sent a DM anyway
Github is dormant since Feb 2018
Facebook has one update in over a year but sent a messge

Instagram is @thujohn and I'm not on there so come someone else ask him to take a look at this issue please?

**Comment by scottybo** [comment]
Let's be careful we don't overwhelm him - there is probably a very good reason why he's not been active online for a while.

**Comment by markdwhite** [comment]
@scottybo 

That's a fair call, though what's the main reason for getting him involved: to be sure this is abandoned, or because of what he needs to do in this process? 

If the former, we possibly only need to do what we think is reasonable. We're not trying to exclude him, but we may need to make the call at some point that we're not likely to hear from him. If the latter, we may be a bit stymied.

**Comment by scottybo** [comment]
I'm more thinking that it would be useful that he at least updates the Readme to point to an 'official' fork. This repo is popular and people will find it, so it would be good to help them on their journey to a maintained alternative.

**Comment by thujohn** [comment]
Hello.

I'm happy to see new developers ready to take over.

I started looking for maintainers but no one came forward…

Today I have disappeared from social networks… for lack of time and for personal reasons…

I see you are setting up an alternative and I will help you there.

I will see to find a just solution to this problem…

**Comment by markdwhite** [comment]
@thujohn 

Thanks so much for responding :-) Sorry if I hit you with a load of messages earlier, but we may have two others willing to be maintainers here.

I'll leave it to you, @scottybo  and @reliq to agree what's best.

**Comment by scottybo** [comment]
@thujohn great to hear from you! Perhaps the best place to start is to ask what you think would be the best direction / route to take. I'm happy to follow your lead.

**Comment by thujohn** [comment]
Can you DM me on twitter please?

**Comment by reliq** [comment]
Hello @thujohn! Thanks for an amazing package.

I'd also like to hear about the outcome of this @scottybo

**Comment by sykezz** [comment]
Good to hear from @thujohn ! I'm interested to know about the future of this project as well :)

**Comment by urukalo** [comment]
just checking .. is there any solution on the horizon for this?

**Comment by atymic** [comment]
Hey all.

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects (needed laravel 6 support, mainly.)

https://github.com/atymic/laravel-twitter

I plan to start going through the bugs/feature requests and adding support them to my fork. I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
Hey all 😄 

I've taken over as the maintainer of this package. I've gone through and triaged all the issues/prs & merged a few urgent ones (laravel 6 support, 7.3 regex fix, autoloading, etc).

Going forward I'd to make it a team effort and bring on other who would like to maintain.  

@scottybo If you'd like I can add you to the repo. Would be keen for your video upload PR to be merged & would love to have you as a maintainer.

@reliq You are also welcome to come on board as a maintainer, let me know :)

If anyone else is keen, feel free to ping me. I'll close this issue as we are back in business 🎉

**Comment by reliq** [comment]
Sure, I'll come on board @atymic.

I do recognize some of the code here.

**Comment by markdwhite** [comment]
Just want to say thanks to everyone who pulled together and got this going again :-)

**Comment by atymic** [comment]
@reliq I've added you as a collaborator :)

@markdwhite Let's make this package awesome again!
