### ISSUE TITLE
Tweet not Post error 401 show when ever try to post tweet status

### ISSUE THREAD

**Issue by ranaraheeltariq** [atymic/twitter#262]
Hello,
Today i'm install this package for make posting on twitter now i'm configure.
i'm try this code it's working correctly

	return Twitter::getCredentials(['format' => 'json']);

but when i'm try to post tweet it's show error 401
`
Route::get('/tweet',function(){
return Twitter::postTweet(['status' => 'This is my tweet from my new Radio Platform twitter application', 'format' => 'json']);
});`
or
` 

       public function twitt(Request $request)
    {
        $request->validate([
            'beforesong' => 'required|string|max:255',
            'aftersong'=> 'required|string|max:255',
            'image'   => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048', ]);
        $beforesong = $request->beforesong;
        $aftersong = $request->aftersong;
        $image = $request->file('image');

        $newTwitte = ['status' => $beforesong.' '.$aftersong];

        
        if(!empty($request->images)){
            foreach ($image as $key => $value) {
                $uploaded_media = Twitter::uploadMedia(['media' => File::get($value->getRealPath())]);
                if(!empty($uploaded_media)){
                    $newTwitte['media_ids'][$uploaded_media->media_id_string] = $uploaded_media->media_id_string;
                }
            }
        }

        $twitter = Twitter::postTweet($newTwitte);

        
        return back();   }`

**Comment by atymic** [comment]
Do you have write permissions with the access token?
