### ISSUE TITLE
Config/app.php Facade

### ISSUE THREAD

**Issue by TheNewSound** [atymic/twitter#276]
This is with laravel-twitter:

I have to manually add 
        'Twitter' => Thujohn\Twitter\Facades\Twitter::class,
to config/app.php

This should be done automagically?

**Comment by atymic** [comment]
The facade should be automatically loaded. I'll check PR a fix if not.

**Comment by atymic** [comment]
Good catch. PR'd the fix here:
https://github.com/atymic/twitter/pull/279

**Comment by atymic** [comment]
Tagged in https://github.com/atymic/twitter/releases/tag/2.2.10
