### ISSUE TITLE
after tweeting: [187] Status is a duplicate 

### ISSUE THREAD

**Issue by holaa2019** [atymic/twitter#281]
Twitter::postTweet(['status' => 'Laravel is beautiful', 'format' => 'json']); throws  [187] Status is a duplicate. , the tweet shows up in twitter, but laravel throws an error message, even the text has never been used so far. I am new to the package and twitter, need help with the wonderful package

**Comment by atymic** [comment]
Thanks for the report, will look into it :)

**Comment by holaa2019** [comment]
My fault. I used Socialte to sign in. When I use atymic/twitter it works.
