### ISSUE TITLE
Application-only authentication

### ISSUE THREAD

**Issue by sykezz** [atymic/twitter#285]
Hi
Any idea on doing requests with [application-only](https://developer.twitter.com/en/docs/basics/authentication/overview/application-only) bearer token (`oauth2/token`)?
I'm trying to use the [Account Activity API](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-premium), and some of these requests require application-only authentication.

**To Reproduce**
The usual `query()` and `get()` methods aren't working with these requests. I've also tried the `apponly_request()` in tmhOAuth as well, but so far no luck.
```
use Thujohn\Twitter\Facades\Twitter;

Twitter::get("account_activity/all/subscriptions/count");
Twitter::get("account_activity/all/{$env}/subscriptions/list");
```

**Expected behavior**
Return HTTP 200 OK with json response.

**Error Messages / Stack Trace**
`Twitter::get("account_activity/all/subscriptions/count")`:
```
RuntimeException with message '[32] Could not authenticate you.'
```
`Twitter::get("account_activity/all/{$env}/subscriptions/list")`:
```
RuntimeException with message '[220] Your credentials do not allow access to this resource'
```

**Version**
master - ad6d0f4b639b71098f03bca39f451e536476ed7c

I've actually [forked](https://github.com/sykezz/twitter/tree/account-activity) this repo to work on this, and so far all API requests have been working except for those application-only requests. Any help would be great! 🙏 Hopefully we could do a PR soon 😄

**Comment by atymic** [comment]
Hey @sykezz 

`tmhOAuth` is a bit of a mess, so I think you'll have a hard time getting the app only ones to work directly through there.

The library is pretty tightly coupled to oauth1, so it's probably easier to write some custom logic to make oauth2 requests. This would probably have to be in the form of another method on the base class that doesn't route through `tmhOAuth`.
I'd prefer if no external deps were required, but it may make it a lot easier (maybe https://github.com/thephpleague/oauth2-client?).

This is a good thing to keep in mind for 3.x as well (we'll need to support oauth 2 and 1).

**Comment by sykezz** [comment]
Aah. Yeah, tmhOAuth is all using OAuth 1.0a, just like how it says on its description. But I just found [tmhOAuthExamples](https://github.com/themattharris/tmhOAuthExamples/blob/master/cli/obtain_bearer.php) is using `oauth2/token` to obtain the app-only bearer token 😆 There's an [issue](https://github.com/themattharris/tmhOAuth/issues/147) about it as well. I'll give it a try.

I've looked into [oauth2-client](https://github.com/thephpleague/oauth2-client) as well, but it doesn't have a provider for Twitter. Probably because it's a bit of a mess on Twitter as well, since [they use both OAuth 1.0a & OAuth2](https://developer.twitter.com/en/docs/basics/authentication/overview/oauth), and don't have the full authentication flow on OAuth2. [oauth1-client](https://github.com/thephpleague/oauth1-client) however does support Twitter.

I noticed that you're getting rid of tmhOAuth in 3.x and replacing with Guzzle oauth-subscriber
 (or are you [planning to use oauth1-client instead](https://github.com/atymic/twitter/issues/265)?). Perhaps [guzzle-oauth2-subscriber](https://github.com/kamermans/guzzle-oauth2-subscriber) could handle OAuth2 support.

**Comment by atymic** [comment]
We'll be using both (v1 and v2) in 3.x.

Even though the oauth2-client doesn't have a pre-built twitter client, it should be a pretty simple flow to implement. The guzzle subscriber look great for 3.x! Thanks for the link

**Comment by sykezz** [comment]
@atymic I believe the OAuth v1 and v2 specs are quite different though. We'll probably have to use both.

Anyway, I've managed to get the [app-only auth working](https://github.com/sykezz/twitter/commit/5d378645a0023a9a2ae326c387796f13032c5774)! 😃 So that covers Account Activity API.

**Comment by atymic** [comment]
Awesome!
Please do create and PR and i'll get it merged/approved :)

**Comment by sykezz** [comment]
Yeah, cool! I've just updated readme as well.
