### ISSUE TITLE
timing out where authentication is required.

### ISSUE THREAD

**Issue by jayenne** [atymic/twitter#291]
**Describe the bug**
I am able to get the last statuses fine but when I try to destroyTweet or postTweet I get a timeout error (see below).

*I get the tweet via spatie/twitter-streaming-api. process it as a job then try to delete the tweet as the author of the tweet with the following:
```
$config = [
                'token' => $user->token,
                'secret' => $user->token_secret
            ];
Twitter::reconfig($config);
$credentials = Twitter::getCredentials(); // <-- corrently returns author credentials.
$response = Twitter::destroyTweet($tweet_id); // <-- timeout :(
```

**To Reproduce**
1. use code example above
2. log::info((array)$responce);
3. See error

**Expected behavior**
I expected it to delete the tweet for the given id as the author (via  $token & $secret within $config)

**Error Messages / Stack Trace**
`Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\ProcessTweet has been attempted too many times or run too long. The job may have previously timed out. in /home/vagrant/code/platform.test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:632`

**Additional context**
within my job I am calling: use Twitter;

any help on this would be greatly appreciated. ty.

**Comment by jayenne** [comment]
my bad ...obvs

**Comment by atymic** [comment]
Did you manage to get it solved?
If not, increase your queue timeout and post the actual error please :)

**Comment by jayenne** [comment]
I did resolve it. It was really stupid user error... I’d not given write access to my twitter app 😆
