### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by eslam-pitechnologies** [atymic/twitter#295]
**Describe the bug**
415 Unsupported Media Type` response
i got this error message when i am sending direct message using Twittet::postDM or Twitter::post()

**To Reproduce**
```
        $recipient = '';
        $data = [
            'format' => 'json',
            'event' => [
                'type' => 'message_create',
                'message_create' => [
                    'target' => [
                        'recipient_id' => $recipient
                    ],
                    'message_data' => [
                        'text' => 'Happy New Year!'
                    ]
                ]
            ]
        ];

        try
        {
            $response = Twitter::post('direct_messages/events/new', $data);
        }
        catch (Exception $e)
        {
            dd(Twitter::logs());
        }

```
**Error Messages / Stack Trace**
"message": "Client error: `POST https://api.twitter.com/1.1/direct_messages/events/new.json` resulted in a `415 Unsupported Media Type` response",

**Version**
"thujohn/twitter": "3.x-dev",

@atymic  @thujohn

**Comment by reliq** [comment]
Hi @eslam-pitechnologies,

Thanks for submitting this! 

Let us know if you still have issues with this after pulling the latest changes.

**Comment by eslam-pitechnologies** [comment]
Hi @reliq 

Thank you so much for your effort the issue in using post direct message has been solved but before i pulling the latest version those tow methods was running well 
*Method*
`Twitter::getMentionsTimeline(['since_id' => $sinceId, 'count' => 20, 'format' => 'json']);`
*Error*
"message": "An unknown request error occurred. See previous messages.",

*Method*
```
Twitter::postTweet([
            'format' => 'json',
            'status' => 'test comment',
            'in_reply_to_status_id' => $request->post_id,
            'auto_populate_reply_metadata' => true,
        ]);
```
*Error*
"message": "[170] Missing required parameter: status.",

**Comment by reliq** [comment]
OK. I have a few thoughts on why this stated happening. Will explore them soon and get back to you with an update.

Thank you.

**Comment by eslam-pitechnologies** [comment]
okay thank you Mr @reliq 
i hope you get back to me as soon as possible because i am using this package in my ordered tasks and the deadline of this task after 5 hours from now  so i hope to solve this problem ASAP and i can deliver in the deadline.

**Comment by reliq** [comment]
Hi @eslam-pitechnologies. This new issues you described have been resolved in the latest commits.

Note the addition of `request_format` parameter for use in situations such as posting direct messages with `Twitter::post()`

Let us know if you still have issues with this after pulling the latest changes.

**Comment by eslam-pitechnologies** [comment]
Thank you so much Mr @reliq  for your effort to help me fixing those issues
the issue has been completely solve thank you . :smiley:  :+1:
