### ISSUE TITLE
linkify() on "tweet_mode = extended" does not work

### ISSUE THREAD

**Issue by dariusj18** [atymic/twitter#304]
**Describe the bug**
linkify() uses $tweet["text"], however it seems that an tweet_mode extended response returns $tweet["full_text"]

**To Reproduce**
1. Request ```Twitter::getUserTimeline(['screen_name' => 'test_username_here',
            'count' => 1,
            'format' => 'object',
            'tweet_mode' => 'extended',
            'include_entities' => 1,
]);```
2. Run `Twitter::linkify($tweet[0])`

**Expected behavior**
A linkified tweet

**Error Messages / Stack Trace**
```Undefined index: text```

**Version**
`2.2.11`

**Comment by dariusj18** [comment]
Mitigated by adding
```
if (!property_exists($tweet, 'text') && property_exists($tweet, 'full_text')) {
  $tweet->text = $tweet->full_text;
}
```
befor calling linkify

**Comment by atymic** [comment]
PR welcome :)
