### ISSUE TITLE
Twitter Class not found

### ISSUE THREAD

**Issue by karajah90** [atymic/twitter#307]
i using Twitter helper like this in my controller .

`return Twitter::getSearch($request->term);`

but i got error like this 

`Error: Class 'App\Http\Controllers\Twitter'`

i configured the package as described in documentation but still need to know how i can use Twitter class

Thanks

**Comment by reliq** [comment]
Hi @karajah90,

Are you still having this issue?

What version are you using?

**Comment by atymic** [comment]
You're missing the backslash to specify the root namespace (and therefore use the facade)

Instead of doing `return Twitter::getSearch($request->term);`, do `return \Twitter::getSearch($request->term);`

**Comment by karajah90** [comment]
I resolve it by import twitter namespace 

`use Twitter` 

Thanks

**Comment by azophy** [comment]
I think the importing part as suggested by @karajah90 should be added to the docs/readme. It not very obvious for everyone who use this package for the first time.
