### ISSUE TITLE
function to get all tweets depending on a Keyword ?

### ISSUE THREAD

**Issue by yassin-hamdan** [atymic/twitter#308]
is there a function that return tweets depending on a Keyword?,
for example: #adidas_superstar i want to get all the tweets on twitter that includes this keyword between two timestamp or like get the last 40 tweets that includes this keyword

**Comment by atymic** [comment]
You can use the search API:
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

`getSearch()` method

**Comment by yassin-hamdan** [comment]
can you give me an example of using this method, i mean like the parameters

**Comment by atymic** [comment]
See: https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators
