### ISSUE TITLE
preg_match_all(): Compilation failed: invalid range in character class at offset 11

### ISSUE THREAD

**Issue by trong2108** [atymic/twitter#314]
preg_match_all( "/$pattern/", $post->post_content, $found );
help me

**Comment by atymic** [comment]
Can you post the stack trace and the call you were making?

**Comment by trong2108** [comment]
> Can you post the stack trace and the call you were making?

/**
	 * @since 4.4.3
	 *
	 * @param array $settings
	 * @param $post_id
	 * @param $post
	 *
	 * @return array
	 */
	public function gridSavePostSettingsId( array $settings, $post_id, $post ) {
		$pattern = $this->getShortcodeRegexForId();
		preg_match_all( "/$pattern/", $post->post_content, $found ); // fetch only needed shortcodes
		$settings['vc_grid_id'] = array();
		if ( is_array( $found ) && ! empty( $found[0] ) ) {
			$to_save = array();
			if ( isset( $found[1] ) && is_array( $found[1] ) ) {
				foreach ( $found[1] as $key => $parse_able ) {
					if ( empty( $parse_able ) || '[' !== $parse_able ) {
						$id_pattern = '/' . $this->grid_id_unique_name . '\:([\w-_]+)/';
						$id_value = $found[4][ $key ];

						preg_match( $id_pattern, $id_value, $id_matches );

						if ( ! empty( $id_matches ) ) {
							$id_to_save = $id_matches[1];

**Comment by atymic** [comment]
That looks like wordpress code. Are you sure it's related to this package?

**Comment by trong2108** [comment]
> That looks like wordpress code. Are you sure it's related to this package?

Yes it's  wordpress code

**Comment by atymic** [comment]
How is it related to this package?
