### ISSUE TITLE
Add minor tweaks to make this usable with queues/jobs.

### ISSUE THREAD

**Issue by WadeShuler** [atymic/twitter#318]
**Is your feature request related to a problem? Please describe.**
Essentially, it's a feature that is lacking from the current state of the library, that will allow this library to be more "real world" usable.

**Describe the solution you'd like**
Allow us to get the current instance of the `Twitter` object itself. Also probably a `loadSession()` method to use a previously saved user's Twitter session.

Something like: `Twitter::getInstance()`

**Describe alternatives you've considered**
Writing my own library lol.

---

The Twitter API limits put us in a box where we have to use queuing, rate-limiting, caching, etc. to pull off lengthly operations that may exceed these limits. This is even further true, when creating an app that would be used by multiple users (ie: 100s or 1,000s) potentially at the same time. Getting the list of the user's Twitter followers (IDs, 5k at a time), at 15 requests per 15 minutes, when they have 100k followers, requires a queue. Once the job is kicked off to a queue, the user's Twitter session (tied with the appropriate job) is lost.

I tried with 2 different browsers, and 2 twitter accounts, and the queued job used the first account in the job process for all of the jobs. The same would be true for a cron job process. So we need a way to pass the actual instance of the Twitter object. I read some other issues, and people mentioned saving the various oauth session keys. Seems hackish, and not sure if it's even possible either. Either way, you would probably also want to encrypt/decrypt the data to not have the keys readable in the database.

I understand that queuing, caching, rate-limiting is beyond the scope of this project. I am not asking to implement it, but to add the necessary features for us to do so ourselves without having to fork this repo to modify it for this simple (and common) task.

**Comment by atymic** [comment]
You should be able to do this already, in a nutshell:

- Store the user's oauth access tokens in your DB somehow
- run `Twitter::reconfig()` and set the the desired user's tokens on the instance
- Run the requests

If you do this in a job, make sure to clear them after it runs, otherwise later jobs that don't configure the client could run using the wrong creds.

**Comment by boutmine** [comment]
@WadeShuler Check skype asap. Harrismarketing
