### ISSUE TITLE
Use with Lumen

### ISSUE THREAD

**Issue by dvdbrk** [atymic/twitter#319]
I'm pulling my hair out for hours, is this library perhaps not compatible with Lumen somehow??

None of the following works:

in app.php
```
$app->register(Thujohn\Twitter\TwitterServiceProvider::class);
$app->register(Thujohn\Twitter\Facades\Twitter::class::class);
$app->alias('Twitter', Thujohn\Twitter\TwitterServiceProvider::class);
$app->alias('Twitter', Thujohn\Twitter\Facades\Twitter::class);
class_alias('Thujohn\Twitter\Facades\Twitter', 'Twitter');
```

or in my controller:
```
use Thujohn\Twitter\TwitterServiceProvider;
use Thujohn\Twitter\TwitterServiceProvider;
use Twitter;

...

$test = Twitter::getHomeTimeline(['count' => 20, 'format' => 'json']);
...
```

It's either a class not found, or not able to call it statically, or just everything stops working...

**Comment by reliq** [comment]
Hello @dvdbrk,

What version are you working with here?

**Comment by dvdbrk** [comment]
8.0

**Comment by atymic** [comment]
Please try with 3.x and we will reopen if you are still having issues.
