### ISSUE TITLE
How to use 2 accounts in 3.x-dev?

### ISSUE THREAD

**Issue by Retropartidas** [atymic/twitter#321]
Hi, I have been using the reconfig method in version 2.3 to be able to use 2 accounts and today I have upgraded to 3.x-dev and I receive an error message that this method does not exist. I have been looking at the code and it is true that I did not find it. Has it been decided to eliminate the reconfig method in this new version for some reason? Will it be included again? Thank you

**Comment by reliq** [comment]
Hello @Retropartidas,

`reconfig` was indeed removed with this [commit](https://github.com/atymic/twitter/commit/da85190b3ecb42292d5c01b722fe1ae2ce9f19bf) for versions `^3.x`.

Please consider the new [usingConfiguration](https://github.com/atymic/twitter/blame/3.x/src/Twitter.php#L124) method as its replacement.

**Comment by Retropartidas** [comment]
Thank you very much @reliq, I did not know that it had been replaced by another method. Would you be so kind as to give an example of use? I'm kind of clumsy, thanks!

**Comment by reliq** [comment]
No problem @Retropartidas. 

You may take a look at its usage in any of the provided service providers. 

See: https://github.com/atymic/twitter/blob/3.x/src/ServiceProviders/PhpDiTwitterServiceProvider.php#L70
or https://github.com/atymic/twitter/blob/3.x/src/ServiceProviders/LaravelTwitterServiceProvider.php#L42

Taking a look at the Configuration [class](https://github.com/atymic/twitter/blob/3.x/src/Configuration.php#L87) and its constructors may be useful as well.

**Comment by Retropartidas** [comment]
Hi @reliq 

I was watching what you say and trying to change key and token before asking for help. I show you what I got

To avoid misunderstandings I clarify that what I want is to be able to use a second twitter account, which is what I did with the reconfig method. Suppose that I am already using the first account, and now in the middle of the application I want to switch accounts. So i have tried this.

No error occurs, but it does not change accounts either, keep writing with the first one. How would it be? Thank you



 $config = ["consumer_key" => ENV('TWITTER_CONSUMER_KEY_2'),
        "consumer_secret"  => ENV('TWITTER_CONSUMER_SECRET_2'),
        "access_token" => ENV('TWITTER_ACCESS_TOKEN_2'),
        "access_token_secret" => ENV('TWITTER_ACCESS_TOKEN_SECRET_2'),
        'api_version' => '1.1',
        'api_url' => 'api.twitter.com',
        'upload_url' => 'upload.twitter.com',
        'authenticate_url' => 'https://api.twitter.com/oauth/authenticate',
        'access_token_url' => 'https://api.twitter.com/oauth/access_token',
        'request_token_url' => 'https://api.twitter.com/oauth/request_token',
        'debug' => env('APP_DEBUG', false),
    ];

    Twitter::usingConfiguration(Atymic\Twitter\Configuration::fromLaravelConfiguration($config));

    Twitter::postTweet(['status' => 'test', 'format' => 'json']);

**Comment by Retropartidas** [comment]
Nobody? I will have to use 2.0 again. I need to use 2 accounts
Cheers

**Comment by reliq** [comment]
Hi @Retropartidas,

This should be possible if you capture the instance returned by `Twitter::usingConfiguration()`.

See the example below:
```php
$altInstance = Twitter::usingConfiguration(\Atymic\Twitter\Configuration::fromLaravelConfiguration($config));

$altInstance->postTweet(['status' => 'test', 'format' => 'json']);
```

**Comment by Retropartidas** [comment]
Thanks reliq!

I stayed close, but I did not make it, following your advice I am now able to use 2 accounts. Thanks a lot

**Comment by reliq** [comment]
You're welcome @Retropartidas

**Comment by akhzir** [comment]
How we can use for multiple users with only one app?

I have a Larvel application, where i want to auto post for admin as well as other multiple users.

i want to use only 1 application. How this is possible.

**Comment by lieto-dk** [comment]
Hi, 
I am trying to use the suggestion proposed from reliq on version 3.2 but im getting  "Call to undefined method Atymic\Twitter\Configuration::fromLaravelConfiguration()" ... is this method still valid or has it been changed in 3.2 ? Can anyone give an updated example as there is no mentioning of usingConfiguration method in the documentation.

**Comment by reliq** [comment]
Hi @lieto-dk, `fromLaravelConfiguration()` was replaced by `createFromConfig()` since version 3.1.0. [(see change)](https://github.com/atymic/twitter/pull/337/files#diff-b7c57c8fe4222bcf6ae806a98fb42f42434997ce6bdddbd37fcf1bf4fb005c2aR61)
