### ISSUE TITLE
RuntimeException [0] Unknown error

### ISSUE THREAD

**Issue by katesaikishore** [atymic/twitter#322]
**Describe the bug**

I have seen the related bugs regrading this but tried no use of it. To work I should always use "php artisan config:cache" command

Version: "thujohn/twitter": "^2.3"
Laravel Version: 6

**Comment by katesaikishore** [comment]
The network depends on the application type bandwidth request. And server response 
If we want to do to use multiple users data as users increase we need to increase the time so the permanent solution

atymic->tmhOAuth.php //which will install with the application

`Change the 'curl_connecttimeout'  => 300, //According to youre application response
`

**Comment by MarkTatterTierney** [comment]
I'm getting this error on an old version of this package. Where should I set the curl timeout?

**Comment by katesaikishore** [comment]
@MarkTatterTierney sry for the late replay. Have you developed in localhost? Try in your hosting server it will work fine.

**Comment by MarkTatterTierney** [comment]
This was happening on two remote servers, but mysteriously seems to have stopped now. No idea why, perhaps an temporary issue with Twitter's servers? Thanks for the reply :-)

**Comment by katesaikishore** [comment]
@MarkTatterTierney Lol! yeah I guess the Twitter API is doing some mystery here. Recently they are developing their V2 modules.
