### ISSUE TITLE
Composer incorrectly says thujohn/twitter is abandoned

### ISSUE THREAD

**Issue by ejunker** [atymic/twitter#324]
**Describe the bug**
Composer says
```
Package thujohn/twitter is abandoned, you should avoid using it. Use atymic/twitter instead.
```
I go to packagist.org and search for `atymic/twitter` but there is no such package. Also the composer.json in this repo still lists the name as `thujohn/twitter`. So unless you intend to move this package to be named `atymic/twitter` I think the abandoned message should be removed from https://packagist.org/packages/thujohn/twitter

**To Reproduce**
run composer install

**Expected behavior**
No warning messages about it being abandoned.

**Comment by atymic** [comment]
You're right, thanks. Fixed :)
