### ISSUE TITLE
Help Me Out This Please | 

### ISSUE THREAD

**Issue by mukeshbadgujar** [atymic/twitter#328]
message: "Non-static method Thujohn\Twitter\Twitter::postTweet() cannot be called statically",…}
exception: "Error"
file: "/home/crivo/Documents/BackEnd/app/Jobs/ProcessTweet.php"
line: 33
message: "Non-static method Thujohn\Twitter\Twitter::postTweet() cannot be called statically"

How Can i call it....

I am Using it >> https://www.itsolutionstuff.com/post/laravel-5-twitter-api-using-thujohn-twitter-composer-package-tutorialexample.html

**Comment by atymic** [comment]
You should using the facade, not the actual object. 

`use Twitter` not `use Thujohn\Twitter\Twitter`
