### ISSUE TITLE
Twitter API version 2 supported?

### ISSUE THREAD

**Issue by ckissi** [atymic/twitter#330]
Does this package support Twitter API version 2?

**Comment by atymic** [comment]
Not yet. I'll look into this. Is there any things not available in v1?

**Comment by xward1** [comment]
Twitter completely overhauled the API in v2. There are so many new features in v2 that it makes v1.1 seem unusable. So yes, it's definitely worth your time to update this package because I don't see many people staying on v1.1 for much longer.

**Comment by atymic** [comment]
Closed in #337 

Massive thanks to @reliq for the PR :D
