### ISSUE TITLE
GuzzleHttp with uploadMedia method

### ISSUE THREAD

**Issue by Retropartidas** [atymic/twitter#332]
**When I upload media with this example of the atymic/twitter documentation**
$uploaded_media = Twitter::uploadMedia(['media' => File::get(public_path('filename.jpg'))]);

**I get always this error**
Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given, called in C:\laravel\vendor\guzzlehttp\psr7\src\MultipartStream.php on line 71 

**Version**
3.x-dev
Laravel 8

**Comment by atymic** [comment]
@reliq could you have a look at this one please?

**Comment by reliq** [comment]
Fixed in #336
