### ISSUE TITLE
FormattingHelpers assume an object

### ISSUE THREAD

**Issue by robjbrain** [atymic/twitter#339]
It seems like all the methods in FormattingHelpers.php assume that you're sending an object.

This means that something like this won't work:

```
$tweet = Twitter::postTweet(['status' => $status, 'response_format' => 'array'])
$url = Twitter::linkTweet($tweet);
//Error: Trying to get property 'user' of non-object
```

This could probably easily be solved using the data_get() Laravel helper.

```php
/*
    public function linkUser($user): string
    {
        return 'https://twitter.com/' . (is_object($user) ? $user->screen_name : $user);
    }

    public function linkTweet($tweet): string
    {
        return $this->linkUser($tweet->user) . '/status/' . $tweet->id_str;
    }
*/
    public function linkUser($user): string
    {
        return 'https://twitter.com/' . (is_string($user) ? $user : data_get($user, 'screen_name'));
    }

    public function linkTweet($tweet): string
    {
        return $this->linkUser(data_get($tweet, 'user')) . '/status/' . data_get($tweet, 'id_str');
    }
```

**Comment by atymic** [comment]
We can't actually use that as you can install the package without laravel. We should fix it none the less.

**Comment by robjbrain** [comment]
I was hoping it would be easy to bring in those helpers via composer, but it actually seems quite difficult unfortunately.

A simpler solution would be then to force an array or an object.

```php
    public function linkUser($user): string
    {
        return 'https://twitter.com/' . (is_string($user) ? $user : ((array)$user)['screen_name']);
    }
```
This would cast it to an array when it's an object or keep it as an array when it's an array.

Probably too big a suggestion for this issue, but would it not be better to always return an Object that implements ArrayAccess rather than having the option to return an object or an array?

**Comment by atymic** [comment]
@robjbrain  I've just PR'd a fix, pretty much what you described (except to deep cast) :)
