### ISSUE TITLE
Twitter Class not found in AuthTrait

### ISSUE THREAD

**Issue by muthu-kc** [atymic/twitter#346]
file: "/var/www/html/lovetrends/vendor/atymic/twitter/src/ApiV1/Traits/AuthTrait.php"
line: 25
message: "Class "Atymic\Twitter\ApiV1\Twitter" not found"

using the latest version

**Comment by atymic** [comment]
Fix tagged in 3.1.4 :) #347

**Comment by muthu-kc** [comment]
gotcha! thanks.
