### ISSUE TITLE
Method not found getRequestToken() 

### ISSUE THREAD

**Issue by muthu-kc** [atymic/twitter#349]
This is what I am trying to do

    ```
use Atymic\Twitter\Facade\Twitter;

   Twitter::usingCredentials($app->token, $app->secret);
    $token =  Twitter::getRequestToken($app->callbackurl);
```

and I am getting this error message

message: "Call to undefined method Atymic\Twitter\Service\Accessor::getRequestToken()"

**Comment by atymic** [comment]
Which API version do you have configured?

**Comment by muthu-kc** [comment]
Latest one.

**Comment by atymic** [comment]
As in, `TWITTER_API_VERSION=2` ?

**Comment by muthu-kc** [comment]
No, it's version 1.1 and latest one in repo.

**Comment by muthu-kc** [comment]
I left it as default one, i didn't configure anything as i am using dynamic
app token and secret.

**Comment by muthu-kc** [comment]
is it going to take time for this?

**Comment by reliq** [comment]
Hi @muthu-kc, that error suggests that you are trying to use that API v1 method with API v2 selected. Please ensure `1.1` is set as `TWITTER_API_VERSION`.

---

https://github.com/atymic/twitter/pull/352 will fix the singleton issue, until then you must call the subsequent methods on the reconfigured instance. e.g.

```php

use Atymic\Twitter\Facade\Twitter;

$twitter = Twitter::usingCredentials($app->token, $app->secret);
$token = $twitter->getRequestToken($app->callbackurl);
```

**Comment by muthu-kc** [comment]
Thank you so much for the support.
