### ISSUE TITLE
Urgent: can't call any functions via Twitter instance

### ISSUE THREAD

**Issue by muthu-kc** [atymic/twitter#350]
$account = AppAccount::get()->first();
 $twitter = Twitter::usingCredentials($account->token, $account->secret);
 $locations = $twitter->getTrendsAvailable();

Error: Call to undefined method Atymic\Twitter\Service\Accessor::getTrendsAvailable()

Please tell me a solution for this. I can't able to code for last day or so.

**Comment by reliq** [comment]
Hi @muthu-kc, that error suggests that you are trying to use that API v1 method with API v2 selected. Please ensure `1.1` is set as `TWITTER_API_VERSION`.
