### ISSUE TITLE
How to manually set the App id and secret?

### ISSUE THREAD

**Issue by muthu-kc** [atymic/twitter#351]
How to override default consumer key and secret?

**Comment by reliq** [comment]
You may do this via `usingCredentials()` method.

e.g.
```php
// ...

$instance = Twitter::usingCredentials($accessToken, $accessTokenSecret, $consumerKey, $consumerSecret);

// ...
```

**Comment by reliq** [comment]
I'll close this now. Please let us know if you have further issues.
