### ISSUE TITLE
Call to undefined method Atymic\Twitter\Service\Accessor::getRequestToken()

### ISSUE THREAD

**Issue by Kamleshpaul** [atymic/twitter#353]
```php
use Atymic\Twitter\Facade\Twitter;

Route::get('twitter/login', ['as' => 'twitter.login', static function () {
    $token = Twitter::getRequestToken(route('twitter.callback'));

    if (isset($token['oauth_token_secret'])) {
        $url = Twitter::getAuthenticateUrl($token['oauth_token']);

        Session::put('oauth_state', 'start');
        Session::put('oauth_request_token', $token['oauth_token']);
        Session::put('oauth_request_token_secret', $token['oauth_token_secret']);

        return Redirect::to($url);
    }

    return Redirect::route('twitter.error');
}]);
``` 
i tried this as per documentaion 

i m getting this error 
>`Call to undefined method Atymic\Twitter\Service\Accessor::getRequestToken()`

using 
* laravel 7.x
* php 7.3
* `"atymic/twitter": "^3.1"`

**Comment by reliq** [comment]
Hi @Kamleshpaul, that error suggests that you are trying to use that API v1 method with API v2 selected. Please ensure `1.1` is set as `TWITTER_API_VERSION`.

**Comment by Kamleshpaul** [comment]
when i changed api `1.1` i got another error


> Atymic\Twitter\Exception\Request\ForbiddenRequestException
A request error occurred. Client error: `GET https://api.twitter.com/oauth/request_token?oauth_callback=http%3A%2F%2Flarryville.test%2Ftwitter%2Fcallback` resulted in a `403 Forbidden` response: <?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. A (truncated...)

`TWITTER_API_VERSION=1.1` and above code in `web.php`

**Comment by reliq** [comment]
Hi @Kamleshpaul. 

That response suggests your client does not have the appropriate permissions. Please ensure that you are using the correct credentials from your developer portal.

See: https://developer.twitter.com/en/portal/projects-and-apps

**Comment by Kamleshpaul** [comment]
@reliq i insatll older version and it works `"atymic/twitter": "^2.3",`

thanks

**Comment by reliq** [comment]
You're welcome. 

I verified it still works in `^3.1`. 

I'll close out this issue now. If you run into further issues please let us know.
