### ISSUE TITLE
How to get Engagement stats

### ISSUE THREAD

**Issue by youngbobby** [atymic/twitter#360]
I am trying to get engagement stats for some twitter accounts and I'm wondering what could be the best way to find this information.

Here are some of the details I am trying to get:
- Average Tweets per day
- Average Retweets per tweet
- Average likes per tweet

Is there a way we can loop through user tweets over a period of time to calculate this information? What are some of the best ways to achieve this with this package ?

**Comment by atymic** [comment]
AFAIK it's enterprise only
https://developer.twitter.com/en/docs/twitter-api/enterprise/engagement-api/overview#:~:text=Overview&text=The%20Engagement%20API%20provides%20access,)%20and%20the%20%2Ftotals%20endpoint.
