### ISSUE TITLE
Count Endpoint

### ISSUE THREAD

**Issue by haleyngonadi** [atymic/twitter#365]
Hi, this is an awesome package. Thank you very much.

Twitter just introduced a new count endpoint and I'm wondering if it can already be implemented using this package and I'm just missing the way to do it?

Here's more information: https://developer.twitter.com/en/docs/twitter-api/tweets/counts/quick-start/recent-tweet-counts

**Comment by reliq** [comment]
Hi @haleyngonadi, thank you for bringing this to our attention. 

This and other newer endpoints are not yet supported but I'll work on adding support for these in the coming days.

**Comment by reliq** [comment]
Please also note that you can currently call any new endpoint by accessing the `Querier` service directly.

e.g. for calling count endpoint:

```php
// ...
$querier = \Atymic\Twitter\Facade\Twitter::getQuerier();
$result = $querier
    ->withOAuth2Client()
    ->get('tweets/counts/recent', ['query' => 'foo']);

dd($result);
```

As per usual, please ensure API v2 is selected. If API v2 is not set as default in your config file you may use the `forApiV2` method.
e.g. 

```php
// ...

$querier = \Atymic\Twitter\Facade\Twitter::forApiV2()
            ->getQuerier();
// ...
```

**Comment by haleyngonadi** [comment]
@reliq WOW.  Exactly what I was looking for. It worked perfectly. Thank you so much! :)

**Comment by reliq** [comment]
You're welcome @haleyngonadi. Glad that solution worked for you!

**Comment by atymic** [comment]
Now also a method @haleyngonadi and @reliq also documented custom queries :)

**Comment by haleyngonadi** [comment]
WOOT, WOOT! Thank you, @atymic :)

I just tried it and it worked as expected! 🎉
