### ISSUE TITLE
Call to undefined method Atymic\Twitter\ApiV1\Service\Twitter::userTweets()

### ISSUE THREAD

**Issue by hammaadd** [atymic/twitter#367]
When I try to fetch user tweets it raises the error and due to lack of documentation wasn't able to understand why and what's causing the issue.

**Comment by atymic** [comment]
As per the docs, `userTweets` is part of the v2 API.

https://github.com/atymic/twitter#twitter-api-v2

See https://github.com/atymic/twitter#twitter-api-versions
