### ISSUE TITLE
What happened to crcHash method?

### ISSUE THREAD

**Issue by beitomartinez** [atymic/twitter#368]
Hi there!
On version 2.x the Facade used to have to crcHash method for weebhook requests, but on version 3, I can't seem to find it.
Is there another way to generate the response token for these requests?

Thanks in advance!

**Comment by atymic** [comment]
cc @reliq

**Comment by reliq** [comment]
Hi @beitomartinez,

Could you please provide a snippet showing how you usually use this method with this package?

**Comment by beitomartinez** [comment]
Hi!
Sure thing.

I use it for the CRC token check that Twitter does when you use webhooks.
For instance, I would do something like this:

```
// Inside the method that handles Twitter CRC request
$response = Twitter::crcHash($request->crc_token);
return new JsonResponse(['response_token' => $response]);
```

**Comment by reliq** [comment]
@beitomartinez, thank you.

#372 should fix this.

**Comment by beitomartinez** [comment]
Thanks!
