### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\parse_query() 

### ISSUE THREAD

**Issue by stephen1204paul** [atymic/twitter#369]
I tried to use 

`Route::get('/userTimeline', function()
{
	return Twitter::getUserTimeline(['screen_name' => 'thujohn', 'count' => 20, 'response_format' => 'json']);
});`

And got the following error

`Call to undefined function GuzzleHttp\Psr7\parse_query() `

Laravel 8.4 version

Using the 3.1 version of the package

Twitter API 1.1 version

**Comment by erkol1emrah** [comment]
I tried to use, i got stuck in the same place.

**Comment by atymic** [comment]
What guzzle version are you using? Could you post a stack trace please.

**Comment by atymic** [comment]
Maybe affected by this major version bump?
https://github.com/guzzle/psr7/blob/master/CHANGELOG.md#removed

**Comment by stephen1204paul** [comment]
Here is my guzzle version.

`"guzzlehttp/guzzle": "^7.0.1",`

Stack trace : [https://flareapp.io/share/B5Zny825#F50](https://flareapp.io/share/B5Zny825#F50)

**Comment by atymic** [comment]
Could you tell me your guzzlehttp/psr7 version (from lock file)?
Thanks!

**Comment by stephen1204paul** [comment]
`
{
            "name": "guzzlehttp/guzzle",
            "version": "7.3.0",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/guzzle.git",
                "reference": "7008573787b430c1c1f650e3722d9bba59967628"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/guzzle/zipball/7008573787b430c1c1f650e3722d9bba59967628",
                "reference": "7008573787b430c1c1f650e3722d9bba59967628",
                "shasum": ""
            },
            "require": {
                "ext-json": "*",
                "guzzlehttp/promises": "^1.4",
                "guzzlehttp/psr7": "^1.7 || ^2.0",
                "php": "^7.2.5 || ^8.0",
                "psr/http-client": "^1.0"
            },
            "provide": {
                "psr/http-client-implementation": "1.0"
            },
            "require-dev": {
                "bamarni/composer-bin-plugin": "^1.4.1",
                "ext-curl": "*",
                "php-http/client-integration-tests": "^3.0",
                "phpunit/phpunit": "^8.5.5 || ^9.3.5",
                "psr/log": "^1.1"
            },
            "suggest": {
                "ext-curl": "Required for CURL handler support",
                "ext-intl": "Required for Internationalized Domain Name (IDN) support",
                "psr/log": "Required for using the Log middleware"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "7.3-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "GuzzleHttp\\": "src/"
                },
                "files": [
                    "src/functions_include.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michael Dowling",
                    "email": "mtdowling@gmail.com",
                    "homepage": "https://github.com/mtdowling"
                },
                {
                    "name": "Márk Sági-Kazár",
                    "email": "mark.sagikazar@gmail.com",
                    "homepage": "https://sagikazarmark.hu"
                }
            ],
            "description": "Guzzle is a PHP HTTP client library",
            "homepage": "http://guzzlephp.org/",
            "keywords": [
                "client",
                "curl",
                "framework",
                "http",
                "http client",
                "psr-18",
                "psr-7",
                "rest",
                "web service"
            ],
            "support": {
                "issues": "https://github.com/guzzle/guzzle/issues",
                "source": "https://github.com/guzzle/guzzle/tree/7.3.0"
            },
            "funding": [
                {
                    "url": "https://github.com/GrahamCampbell",
                    "type": "github"
                },
                {
                    "url": "https://github.com/Nyholm",
                    "type": "github"
                },
                {
                    "url": "https://github.com/alexeyshockov",
                    "type": "github"
                },
                {
                    "url": "https://github.com/gmponos",
                    "type": "github"
                }
            ],
            "time": "2021-03-23T11:33:13+00:00"
        },
`

**Comment by stephen1204paul** [comment]
It is 7.3.0.

**Comment by atymic** [comment]
It doesn't have that version. I think you're looking at the guzzle version not the psr7 version
https://github.com/guzzle/psr7/releases

**Comment by stephen1204paul** [comment]
Sorry about that.

It is "version": "2.0.0",

**Comment by atymic** [comment]
Ok, issue looks to be `guzzlehttp/oauth-subscriber` doesn't support psr7 2.0
Fix in this PR, i'll tag a new version that locks psr7 to 1.x for the time being until and update is merged there.

**Comment by atymic** [comment]
Upgrade to 3.1.11
https://github.com/atymic/twitter/releases/tag/3.1.11

**Comment by stephen1204paul** [comment]
Great it works now.

Thank you.

**Comment by ssheduardo** [comment]
> Upgrade to 3.1.11 https://github.com/atymic/twitter/releases/tag/3.1.11

Hello, first of all thank you very much for this package which helps us a lot.
I have the problem of parse_query, the problem is that my system has PHP 7.3 and I am migrating to Laravel 7, I see that the requirement to use version 3.1.11 is to have PHP 7.4, is there any solution for those who still use PHP 7.3?
Thank you.

**Comment by atymic** [comment]
Downgrade your guzzle so you can use the old package version.
