### ISSUE TITLE
Working on macbook but not running on ubuntu

### ISSUE THREAD

**Issue by afrazahmmad** [atymic/twitter#374]
Hi dear!
Thanks for creating great package.
I am facing a strange issue 

I have same version of php i.e. 7.4.22 on my local (macbook) and live server (ubuntu)
This is package running awesome but shows below error on server (ubuntu)
Details:
php 7.4.22
laravel :7.30.4
atymic/twitter 3.1.13

![image](https://user-images.githubusercontent.com/22490945/127651193-b7466222-659b-4d6e-9a2b-25e70d65b647.png)

**Comment by atymic** [comment]
Can you post the output of phpinfo()?

My guess is your web server is running a different version of PHP than you think.
