### ISSUE TITLE
How to get media from direct message?

### ISSUE THREAD

**Issue by dedefajriansyah** [atymic/twitter#376]
Cannot retrieving media from incoming direct message

Example: https://ton.twitter.com/1.1/ton/data/dm/1430512567705763852/1430512324612300806/UK9OrmkN.jpg

**Comment by stack74** [comment]
```
Twitter::getQuerier()->directQuery($image_url, 'GET', [
      'response_format' => 'json'
]);
```
The directQuery call does not add the twitter api endpoints. The json response format is a workaround to prevent the json_encode on the raw image result.
