### ISSUE TITLE
Call to undefined method Atymic\Twitter\Service\Accessor::postTweet()

### ISSUE THREAD

**Issue by nerocil** [atymic/twitter#381]
How to fix this issue 
`Call to undefined method Atymic\Twitter\Service\Accessor::postTweet()`

**Comment by koossaayy** [comment]
Could you provide more details ? Which version of API are you using ? The steps to produce the error ?

**Comment by MarceloFonsecaD2B** [comment]
Looks like that this method is not implemented in API v2.

**Comment by jayenne** [comment]
> 

This was the day Twitter switch off API v1.1 

-- are there any plans to re-impletent sending posts & dm's to twitter from this package?

**Comment by ahosker** [comment]
I wish I read this before tying to implement this package, lol.

**Comment by nerocil** [comment]
Checkout this library its solve my problem
[https://github.com/danieldevine/bird-elephant](https://github.com/danieldevine/bird-elephant)

**Comment by ahosker** [comment]
Thanks @nerocil I went with this in the end. https://github.com/abraham/twitteroauth
