### ISSUE TITLE
How we can use for multiple users with only one app?

### ISSUE THREAD

**Issue by akhzir** [atymic/twitter#382]
How we can use for multiple users with only one app?

I have a Larvel application, where i want to auto post for admin as well as other multiple users.

i want to use only 1 application. How this is possible.

**Comment by natsumeaurlia** [comment]
@akhzir 
hi.
I had the same problem.
I think I can solve it by using `usingCredentials`.

Use the method described in the readme or [Socialite](https://laravel.com/docs/8.x/socialite#retrieving-user-details) to save the `access token` and `access token secret` of the integrated account in the DB.
Then, just pass the `access token` and `access token secret` to `usingCredentials`.

![スクリーンショット 2022-02-12 22 37 00](https://user-images.githubusercontent.com/40763821/153713718-02c4ff61-5613-478b-8671-f0df2de6cf76.png)

```
$account = Account::first();
$twitter = \Atymic\Twitter\Facade\Twitter::usingCredentials($account->access_token, $account->access_token_secret);
dd($twitter->getSearch(['q' => 'twitter']));
```

Alternatively, the Twitter account can register with Twitter Developer to get Access Token, Consumer Key...

I hope this helps.
