### ISSUE TITLE
Why empty array is required for: Twitter::getTweet(12345678911, []) ?

### ISSUE THREAD

**Issue by foremtehan** [atymic/twitter#397]
I'm using the package with laravel, Why the second argument is required for parameter ?

v3:

```php
Twitter::getTweet(12345678911, [])
```

Why not just using `Twitter::getTweet(12345678911)`? 

If this is a laravel package why not just return a collection ?

**Comment by atymic** [comment]
Feel free to PR a fix to add the default arg.
