### ISSUE TITLE
twitter postTwitter method doesn't work in laravel 9

### ISSUE THREAD

**Issue by DavidAmirKham** [atymic/twitter#399]
I configured the following steps but make error postTweet method of laravel 9.
Error: Call to undefined method Atymic\Twitter\Service\Accessor::postTweet()

1. composer require atymic/twitter

2. php artisan vendor:publish --provider="Atymic\Twitter\ServiceProvider\LaravelServiceProvider"

3. php artisan vendor:publish --provider="Atymic\Twitter\ServiceProvider\LaravelServiceProvider"

4.
use Atymic\Twitter\Facade\Twitter;
public function tweet()
        Twitter::postTweet(['status' => 'Laravel is beautiful', 'response_format' => 'json']);
}

**Comment by reliq** [comment]
Hi @DavidAmirKham. The `postTweet` method is not currently explicitly implemented for Twitter API v2. 

You can however still post a tweet with this package in the following way:

```php
// ...

use Atymic\Twitter\Contract\Http\Client;

// ...

$querier = Twitter::forApiV2()->getQuerier();
$result = $querier->post(
    'tweets', 
    [
        Client::KEY_REQUEST_FORMAT => Client::REQUEST_FORMAT_JSON,
        'text' => 'my tweet'
    ]
);

// ...
``` 

NB. call to `forApiV2()` is optional.

`$result` will contain the posted tweet:

![image](https://user-images.githubusercontent.com/2624812/191613594-5015294a-c0dc-4377-8ae2-6101f8cf76f3.png)
