### ISSUE TITLE
Unable to install the package with Laravel 9.x

### ISSUE THREAD

**Issue by joshbingtech** [atymic/twitter#406]
Tried to install it under Laravel 9.19 and got the following error:

`Problem 1
    - atymic/twitter 3.1.15 requires php-di/php-di ^6.2 -> satisfiable by php-di/php-di[6.2.0, ..., 6.4.x-dev].
    - atymic/twitter[3.1.0, ..., 3.1.14] require illuminate/support 6 - 8 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - php-di/php-di[6.2.0, ..., 6.4.x-dev] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. 
    - Root composer.json requires atymic/twitter ^3.1 -> satisfiable by atymic/twitter[3.1.0, ..., 3.1.15].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

After running `composer require atymic/twitter -W`, got the following error again.

`Problem 1
    - Root composer.json requires laravel/framework ^9.19, found laravel/framework[v9.19.0, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    
  Problem 2
    - laravel/sanctum is locked to version v3.0.1 and an update of this package was not requested.
    - laravel/sanctum v3.0.1 requires illuminate/console ^9.21 -> found illuminate/console[v9.21.0, ..., 9.x-dev] but these were not loaded, 
likely because it conflicts with another require.

  Problem 3
    - laravel/tinker is locked to version v2.7.3 and an update of this package was not requested.
    - laravel/tinker v2.7.3 requires illuminate/console ^6.0|^7.0|^8.0|^9.0 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require. 
          
  Problem 4
    - laravel/ui is locked to version v4.1.1 and an update of this package was not requested.
    - laravel/ui v4.1.1 requires illuminate/console ^9.21 -> found illuminate/console[v9.21.0, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    
  Problem 5
    - laravel/sail is locked to version v1.16.3 and an update of this package was not requested.
    - laravel/sail v1.16.3 requires illuminate/console ^8.0|^9.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - 
  Problem 6
    - spatie/flare-client-php 1.3.1 requires illuminate/pipeline ^8.0|^9.0 -> found illuminate/pipeline[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, 
..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - spatie/laravel-ignition 1.6.2 requires spatie/flare-client-php ^1.0.1 -> satisfiable by spatie/flare-client-php[1.3.1].
    - spatie/laravel-ignition is locked to version 1.6.2 and an update of this package was not requested.`

Not sure how to resolve it. Can anyone help me?

**Comment by meyer59** [comment]
I have the same issue
```
Using version ^3.1 for atymic/twitter
./composer.json has been updated
Running composer update atymic/twitter
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - atymic/twitter 3.1.15 requires php-di/php-di ^6.2 -> satisfiable by php-di/php-di[6.2.0, ..., 6.4.x-dev].
    - atymic/twitter[3.1.0, ..., 3.1.14] require illuminate/support 6 - 8 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were n
ot loaded, likely because it conflicts with another require.
    - php-di/php-di[6.2.0, ..., 6.4.x-dev] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial upd
ate and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires atymic/twitter ^3.1 -> satisfiable by atymic/twitter[3.1.0, ..., 3.1.15].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require atymic/twitter:*" to figure out if any version is installable, or "composer req
uire atymic/twitter:^2.1" if you know which you need.
```
