### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by YOzaz** [atymic/twitter#62]
Marking it here to keep it on track - Twitter is going to add video upload support soon, so I would love this library to be updated as well (for Laravel 4).

https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/31258/15

**Comment by beeseenmedia** [comment]
or laravel 5 :)

**Comment by YOzaz** [comment]
Any update for this?
I think we need chunked upload possibility, described here: https://dev.twitter.com/rest/reference/post/media/upload-chunked

**Comment by beeseenmedia** [comment]
i edited the code to add video support. you can see it here.  Note there is a second variable to the function which specified if media is a video

https://github.com/beeseenmedia/twitter/commit/d875ea630592f88c29523d060292c65a3f3dfd13

**Comment by YOzaz** [comment]
@beeseenmedia thanks for reply. In general, I think second parameter can be omited by detecting MIME type form media source.

**Comment by beeseenmedia** [comment]
indeed. it can. I just wanted a quick and dirty way to do it but yes a mime detection would make it neater, feel free to fork, modify and commit.

**Comment by YOzaz** [comment]
Pull request is here: https://github.com/thujohn/twitter/pull/105.
@thujohn any chance you'll merge this soon?

**Comment by YOzaz** [comment]
Updated pull request to avoid memory issues: https://github.com/thujohn/twitter/pull/136

**Comment by scottybo** [comment]
Just in case someone else finds this thread, I've forked this package and added video support (docs for video near the bottom of the readme): https://github.com/scottybo/twitter

**Comment by FrankChinedu** [comment]
@scottybo i tried running the upload video but i get RuntimeException (400)

**Comment by atymic** [comment]
@reliq is this supported in 3.x?

**Comment by reliq** [comment]
> @reliq is this supported in 3.x?

Unfortunately, I'm not able to confirm this actually works any better OTB in v3, `uploadMedia` works as it did in v2. 

If this continues to be an issue for some people I could invest some more time into it.

**Comment by atymic** [comment]
This can be closed now right @reliq?

**Comment by reliq** [comment]
Yes. This is fixed @atymic
