### ISSUE TITLE
linkTweet vs. linkify API inconsistency

### ISSUE THREAD

**Issue by memco** [atymic/twitter#66]
Both `linkTweet` and `linkify` take a `$tweet` as an argument, but `linkTweet` expects an object and `linkify` expects a string (really `$tweet->text`).  At the very least, updating the docs would be good, but I would think a better approach would be to pass the object for both functions and let the function do the right thing.  Can submit a PR for either, but wanted to check if there was a preferred method.

**Comment by atymic** [comment]
Closed in #67
