### ISSUE TITLE
Error Upload Large Image

### ISSUE THREAD

**Issue by rybias87** [atymic/twitter#92]
When I upload the image using Laravel4 it's not working on a large image. Only for small image.

array_key_exists() expects parameter 2 to be array, null given

**Comment by YOzaz** [comment]
Hi, you can use my fork https://github.com/YOzaz/twitter for now - you need to upload media in chunks.
Until this pull request will be merged: https://github.com/thujohn/twitter/pull/136.

**Comment by g33kidd** [comment]
THANK you @YOzaz ! You have no idea how much this helped me! 👍  I'm surprised this hasn't been merged yet... It works unlike all the other chunked upload methods I've found. You sir, are a god.

**Comment by YOzaz** [comment]
No probs @g33kidd, glad it was helpful :+1:
Hopefully it will be merged soon. @thujohn it's now tested on 2 systems at least ;)

**Comment by atymic** [comment]
Closing as this is a 2.x bug.
